# Generated by Django 5.2.6 on 2025-11-12 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aknaszám', models.IntegerField()),
                ('nev', models.CharField(max_length=100)),
                ('egyik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('masik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masik', to=settings.AUTH_USER_MODEL)),
                ('nyertes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nyertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Játék',
                'verbose_name_plural': 'Játékok',
            },
        ),
    ]
